CREATE TABLE nobel_win(
YEARS INT,
SUBJECT VARCHAR(255),
WINNER VARCHAR(255),
COUNTRY VARCHAR(255),
CATEGORY VARCHAR(255)
);

SELECT * FROM nobel_win WHERE YEARS >1972 AND WINNER IN ('Menachem Begin','Yitzhak Rabin');



