CREATE TABLE nobel_win(
YEARS INT,
SUBJECT VARCHAR(255),
WINNER VARCHAR(255),
COUNTRY VARCHAR(255),
CATEGORY VARCHAR(255)
);

SELECT * FROM nobel_win  WHERE (SUBJECT ='Physics' AND YEARS=1970) UNION (SELECT * FROM nobel_win  WHERE (SUBJECT ='Economics' AND YEARS=1971));





