CREATE TABLE nobel_win(
YEARS INT,
SUBJECT VARCHAR(255),
WINNER VARCHAR(255),
COUNTRY VARCHAR(255),
CATEGORY VARCHAR(255)
);

SELECT * FROM nobel_win WHERE (SUBJECT ='Physiology' AND YEARS<1971) UNION (SELECT * FROM nobel_win WHERE (SUBJECT ='Peace' AND YEARS>=1974));






